### ISSUE TITLE
Module riplib.plugin seems to be missing from the repo

### ISSUE THREAD

**Issue by taw123** [bolodev/osxripper#1]
Greetings. Stumbled upon your project t while trying to debug some problems I am attributing to the ~/Library/Accounts/Accounts4.sqlite.

I cloned your Repo local but when executing the script:
`sudo python3 osxripper.py --help
`

I get back the following error:
```
Traceback (most recent call last):
  File "/Users/weyer_l/Documents/Development/GitHub Projects/osxripper/osxripper.py", line 8, in <module>
    from plugins.osx_version import OSXVersion
  File "/Users/weyer_l/Documents/Development/GitHub Projects/osxripper/plugins/osx_version.py", line 5, in <module>
    from riplib.plugin import Plugin
ModuleNotFoundError: No module named 'riplib.plugin'

```
Doesn't seem to be an issue of privileges or execution rights, and don't see the file in question **riplib.plugin** locally or in your repo
Local listing below...

```
[ 384]  .
├── [ 34K]  LICENSE
├── [2.0K]  README.md
├── [7.0K]  osxripper.py
├── [7.1K]  osxripper_mt.py
├── [ 256]  plugins
│   ├── [3.4K]  Summary.py
│   ├── [   0]  __init__.py
│   ├── [ 128]  __pycache__
│   │   ├── [ 173]  __init__.cpython-39.pyc
│   │   └── [2.4K]  osx_version.cpython-39.pyc
│   ├── [2.9K]  osx
│   │   ├── [ 21K]  AirportPreferences.py
│   │   ├── [ 11K]  AlfPlist.py
│   │   ├── [2.3K]  Applications.py
│   │   ├── [2.8K]  Autoruns.py
│   │   ├── [ 30K]  BluetoothPlist.py
│   │   ├── [2.5K]  BootFlags.py
│   │   ├── [8.4K]  CacheEncryptedDatabase.py
│   │   ├── [4.0K]  CupsPrintersPlist.py
│   │   ├── [2.8K]  DeletedUsersPlist.py
│   │   ├── [5.3K]  DhcpLeasesPlist.py
│   │   ├── [2.7K]  DiagnosticReportingNetworks.py
│   │   ├── [2.9K]  DiagnosticReportingNetworksNew.py
│   │   ├── [4.4K]  DocumentRevisions.py
│   │   ├── [2.7K]  GKRearmTimer.py
│   │   ├── [4.9K]  InstallHistory.py
│   │   ├── [5.8K]  InteractionDatabase.py
│   │   ├── [1.9K]  KernelExtensions.py
│   │   ├── [2.9K]  LibraryStatus.py
│   │   ├── [5.1K]  LocationdClientsPlist.py
│   │   ├── [2.5K]  LoginWindowPlist.py
│   │   ├── [2.0K]  MobileBackupList.py
│   │   ├── [7.2K]  NetworkInterfaces.py
│   │   ├── [ 22K]  NetworkPreferences.py
│   │   ├── [2.9K]  Playlists.py
│   │   ├── [5.0K]  QuicklookThumbnailCache.py
│   │   ├── [2.0K]  RootShellHistory.py
│   │   ├── [2.9K]  SiriLog.py
│   │   ├── [2.8K]  SmbServer.py
│   │   ├── [8.1K]  SystemAccountsPlist.py
│   │   ├── [4.2K]  SystemAuthDB.py
│   │   ├── [5.4K]  SystemAuthPlist.py
│   │   ├── [6.9K]  SystemGlobalPreferences.py
│   │   ├── [5.3K]  SystemKnowledgeC.py
│   │   ├── [2.7K]  SystemLaunchdDisabled.py
│   │   ├── [3.6K]  SystemLogs.py
│   │   ├── [6.9K]  SystemNetUsage.py
│   │   ├── [3.4K]  SystemNetworkExtension.py
│   │   ├── [3.6K]  SystemSnapshots.py
│   │   ├── [ 12K]  SystemTime.py
│   │   ├── [3.1K]  SystemVersionPlist.py
│   │   ├── [2.8K]  SystemWidgets.py
│   │   ├── [ 11K]  TimeMachinePlist.py
│   │   ├── [7.9K]  UserAccountsPlist.py
│   │   ├── [7.0K]  UsersAccounts3.py
│   │   ├── [4.9K]  UsersAccounts4.py
│   │   ├── [2.2K]  UsersApplications.py
│   │   ├── [4.3K]  UsersBashHistory.py
│   │   ├── [6.9K]  UsersChromeCookies.py
│   │   ├── [4.3K]  UsersChromeDownloads.py
│   │   ├── [3.9K]  UsersChromeFavicons.py
│   │   ├── [4.4K]  UsersChromeHistory.py
│   │   ├── [6.1K]  UsersChromeLoginData.py
│   │   ├── [3.5K]  UsersChromePlist.py
│   │   ├── [ 18K]  UsersChromeWebData.py
│   │   ├── [5.4K]  UsersCommercePlist.py
│   │   ├── [2.9K]  UsersContainers.py
│   │   ├── [4.8K]  UsersCyberGhost.py
│   │   ├── [3.4K]  UsersCyberGhostLogs.py
│   │   ├── [2.8K]  UsersDiskUtilityLog.py
│   │   ├── [4.2K]  UsersDockPlist.py
│   │   ├── [4.7K]  UsersFaceTimeLog.py
│   │   ├── [4.5K]  UsersFinderPlist.py
│   │   ├── [3.0K]  UsersFsckHfsLog.py
│   │   ├── [2.7K]  UsersIosBackupList.py
│   │   ├── [6.5K]  UsersKnowledgeC.py
│   │   ├── [2.6K]  UsersLaunchAgents.py
│   │   ├── [6.7K]  UsersLoginWindowPlist.py
│   │   ├── [5.1K]  UsersMozillaFirefoxCookies.py
│   │   ├── [4.5K]  UsersMozillaFirefoxFormHistory.py
│   │   ├── [6.6K]  UsersMozillaFirefoxPlaces.py
│   │   ├── [3.1K]  UsersMozillaFirefoxPlist.py
│   │   ├── [3.9K]  UsersNetAuthAgentPlist.py
│   │   ├── [8.9K]  UsersQuarantineEventsV2.py
│   │   ├── [4.1K]  UsersRecentApplications.py
│   │   ├── [4.0K]  UsersRecentDocuments.py
│   │   ├── [4.0K]  UsersRecentHosts.py
│   │   ├── [5.7K]  UsersRecentItemsPlist.py
│   │   ├── [6.6K]  UsersSafariCache.py
│   │   ├── [8.7K]  UsersSafariDownloadPlist.py
│   │   ├── [ 10K]  UsersSafariHistory.py
│   │   ├── [5.9K]  UsersSafariLastSession.py
│   │   ├── [4.5K]  UsersSafariMetadataHistory.py
│   │   ├── [8.1K]  UsersSafariPlist.py
│   │   ├── [4.1K]  UsersSafariTopSites.py
│   │   ├── [4.2K]  UsersSafariWebBookmarks.py
│   │   ├── [4.2K]  UsersSafariWebIcons.py
│   │   ├── [5.3K]  UsersSidebarPlist.py
│   │   ├── [2.8K]  UsersTrueCrypt.py
│   │   ├── [7.8K]  UsersTunnelBear.py
│   │   ├── [2.8K]  UsersVMWare.py
│   │   ├── [6.4K]  WifiMessageTracer.py
│   │   └── [   0]  __init__.py
│   └── [2.6K]  osx_version.py
├── [ 256]  riplib
│   ├── [3.8K]  Plugin.py
│   ├── [   0]  __init__.py
│   ├── [  96]  __pycache__
│   │   └── [ 172]  __init__.cpython-39.pyc
│   ├── [ 20K]  ccl_bplist.py
│   └── [3.1K]  osxripper_time.py
└── [2.9K]  wiki.md

5 directories, 107 files

```

Any thoughts?  Is riplib/Plugin.py somehow supposed to be transformed into the base plugin templet the error speaks about?

Thanks for any help you can offer!

**Comment by bolodev** [comment]
Issue with development on Windows not properly handling upper and lowercase file names. Renaming with 

mv Plugin.py plugin.py

Seems to work on Linux (Ubuntu)

**Comment by bolodev** [comment]
Updated Summary.py to summary.py too, seems to work
